"""domaine pricing

Revision ID: b95ec122313a
Revises: d903dc68c461
Create Date: 2026-09-15 14:11:40.821266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b95ec122313a'
down_revision: Union[str, Sequence[str], None] = 'd903dc68c461'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendors',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('type', sa.Enum('supermarket', 'market', 'grocery', 'official_reference', name='vendor_type'), nullable=False),
    sa.Column('zone', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('latitude IS NULL OR (latitude BETWEEN -90 AND 90)', name=op.f('ck_vendors_latitude_range')),
    sa.CheckConstraint('longitude IS NULL OR (longitude BETWEEN -180 AND 180)', name=op.f('ck_vendors_longitude_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendors'))
    )
    op.create_index(op.f('ix_vendors_slug'), 'vendors', ['slug'], unique=True)
    op.create_index('ix_vendors_zone_active', 'vendors', ['zone', 'is_active'], unique=False)
    op.create_table('dish_cost_estimates',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('dish_id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=True),
    sa.Column('total_cost_min', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_cost_median', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_cost_max', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('coverage_ratio', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('oldest_observation_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('coverage_ratio BETWEEN 0 AND 1', name=op.f('ck_dish_cost_estimates_coverage_range')),
    sa.CheckConstraint('total_cost_median IS NULL OR total_cost_max IS NULL OR total_cost_median <= total_cost_max', name=op.f('ck_dish_cost_estimates_median_le_max')),
    sa.CheckConstraint('total_cost_min IS NULL OR total_cost_median IS NULL OR total_cost_min <= total_cost_median', name=op.f('ck_dish_cost_estimates_min_le_median')),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], name=op.f('fk_dish_cost_estimates_dish_id_dishes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_dish_cost_estimates_vendor_id_vendors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dish_cost_estimates')),
    sa.UniqueConstraint('dish_id', 'vendor_id', name='uq_dish_cost_estimates_scope')
    )
    op.create_index(op.f('ix_dish_cost_estimates_dish_id'), 'dish_cost_estimates', ['dish_id'], unique=False)
    op.create_index(op.f('ix_dish_cost_estimates_vendor_id'), 'dish_cost_estimates', ['vendor_id'], unique=False)
    op.create_table('ingredient_prices',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ingredient_id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('unit', sa.String(length=40), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.Enum('manual', 'official', 'community', 'scraping', name='price_source'), nullable=False),
    sa.Column('collected_by', sa.String(length=128), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('outlier_confirmed', sa.Boolean(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.CheckConstraint('confidence IS NULL OR (confidence BETWEEN 0 AND 1)', name=op.f('ck_ingredient_prices_confidence_range')),
    sa.CheckConstraint('price > 0', name=op.f('ck_ingredient_prices_price_positive')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_ingredient_prices_quantity_positive')),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], name=op.f('fk_ingredient_prices_ingredient_id_ingredients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_ingredient_prices_vendor_id_vendors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingredient_prices')),
    sa.UniqueConstraint('ingredient_id', 'vendor_id', 'collected_at', 'unit', 'source', name='uq_ingredient_prices_observation')
    )
    op.create_index(op.f('ix_ingredient_prices_collected_at'), 'ingredient_prices', ['collected_at'], unique=False)
    op.create_index(op.f('ix_ingredient_prices_ingredient_id'), 'ingredient_prices', ['ingredient_id'], unique=False)
    op.create_index('ix_ingredient_prices_lookup', 'ingredient_prices', ['ingredient_id', 'collected_at'], unique=False)
    op.create_index(op.f('ix_ingredient_prices_vendor_id'), 'ingredient_prices', ['vendor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingredient_prices_vendor_id'), table_name='ingredient_prices')
    op.drop_index('ix_ingredient_prices_lookup', table_name='ingredient_prices')
    op.drop_index(op.f('ix_ingredient_prices_ingredient_id'), table_name='ingredient_prices')
    op.drop_index(op.f('ix_ingredient_prices_collected_at'), table_name='ingredient_prices')
    op.drop_table('ingredient_prices')
    op.drop_index(op.f('ix_dish_cost_estimates_vendor_id'), table_name='dish_cost_estimates')
    op.drop_index(op.f('ix_dish_cost_estimates_dish_id'), table_name='dish_cost_estimates')
    op.drop_table('dish_cost_estimates')
    op.drop_index('ix_vendors_zone_active', table_name='vendors')
    op.drop_index(op.f('ix_vendors_slug'), table_name='vendors')
    op.drop_table('vendors')
    # ### end Alembic commands ###

    # Ajouté à la main : `op.drop_table` ne supprime pas les types énumérés
    # PostgreSQL. Sans ces lignes, `vendor_type` et `price_source` survivraient
    # au downgrade et feraient échouer le prochain upgrade sur un « type already
    # exists » — la migration ne serait donc pas réversible.
    sa.Enum(name='price_source').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='vendor_type').drop(op.get_bind(), checkfirst=True)
