"""schema initial lots 1 et 2

Revision ID: d903dc68c461
Revises: 
Create Date: 2026-08-27 14:49:58.873562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd903dc68c461'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_app_settings'))
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('external_user_id', sa.String(length=128), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=True),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('result', sa.Enum('success', 'failure', 'denied', name='audit_result'), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_logs_action_occurred_at', 'audit_logs', ['action', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_correlation_id'), 'audit_logs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_occurred_at'), 'audit_logs', ['occurred_at'], unique=False)
    op.create_index('ix_audit_logs_user_occurred_at', 'audit_logs', ['external_user_id', 'occurred_at'], unique=False)
    op.create_table('dishes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('meal_types', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('origin', sa.String(length=120), nullable=True),
    sa.Column('prep_time_min', sa.Integer(), nullable=False),
    sa.Column('cook_time_min', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.Enum('easy', 'medium', 'hard', name='difficulty'), nullable=False),
    sa.Column('servings', sa.Integer(), nullable=False),
    sa.Column('kcal_portion', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('protein_portion', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('carbs_portion', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('fat_portion', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('fiber_portion', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('nutrition_computed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cost_class', sa.Enum('economical', 'medium', 'high', name='cost_class'), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('compatible_goals', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('compatible_restrictions', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('draft', 'pending_validation', 'validated', 'published', 'archived', 'rejected', name='dish_status'), nullable=False),
    sa.Column('author_id', sa.String(length=128), nullable=True),
    sa.Column('validated_by', sa.String(length=128), nullable=True),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("compatible_goals <@ ARRAY['weight_loss', 'weight_maintenance', 'weight_gain', 'muscle_gain', 'balanced_diet', 'habit_improvement']::text[]", name=op.f('ck_dishes_compatible_goals_known')),
    sa.CheckConstraint("compatible_restrictions <@ ARRAY['vegetarian', 'vegan', 'no_pork', 'no_alcohol', 'lactose_free', 'gluten_free', 'religious', 'forbidden_food', 'custom']::text[]", name=op.f('ck_dishes_compatible_restrictions_known')),
    sa.CheckConstraint("meal_types <@ ARRAY['breakfast', 'lunch', 'dinner', 'snack']::text[]", name=op.f('ck_dishes_meal_types_known')),
    sa.CheckConstraint("status <> 'published' OR (validated_by IS NOT NULL AND validated_at IS NOT NULL)", name=op.f('ck_dishes_published_requires_validation')),
    sa.CheckConstraint("status <> 'published' OR nutrition_computed_at IS NOT NULL", name=op.f('ck_dishes_published_requires_computed_nutrition')),
    sa.CheckConstraint('cardinality(meal_types) > 0', name=op.f('ck_dishes_meal_types_not_empty')),
    sa.CheckConstraint('estimated_cost IS NULL OR estimated_cost >= 0', name=op.f('ck_dishes_cost_not_negative')),
    sa.CheckConstraint('prep_time_min >= 0 AND cook_time_min >= 0', name=op.f('ck_dishes_times_not_negative')),
    sa.CheckConstraint('servings > 0', name=op.f('ck_dishes_servings_positive')),
    sa.CheckConstraint('validated_by IS NULL OR author_id IS NULL OR validated_by <> author_id', name=op.f('ck_dishes_validator_differs_from_author')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dishes'))
    )
    op.create_index('ix_dishes_meal_types_gin', 'dishes', ['meal_types'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_dishes_slug'), 'dishes', ['slug'], unique=True)
    op.create_index('ix_dishes_status_meal_types', 'dishes', ['status', 'meal_types'], unique=False)
    op.create_table('ingredients',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('category', sa.Enum('cereals', 'vegetables', 'fruits', 'meats', 'fish', 'dairy', 'legumes', 'beverages', 'oils', 'spices', 'processed', name='ingredient_category'), nullable=False),
    sa.Column('reference_unit', sa.Enum('g', 'ml', 'unit', name='reference_unit'), nullable=False),
    sa.Column('kcal_100', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('protein_100', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('carbs_100', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('fat_100', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('fiber_100', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('nutrition_source', sa.String(length=255), nullable=False),
    sa.Column('allergens', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('allergen_source', sa.String(length=255), nullable=True),
    sa.Column('allergen_verified_by', sa.String(length=128), nullable=True),
    sa.Column('allergen_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('restriction_flags', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('locally_available', sa.Boolean(), nullable=False),
    sa.Column('seasonality', postgresql.ARRAY(sa.SmallInteger()), nullable=False),
    sa.Column('density_g_per_ml', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('active', 'draft', 'archived', name='ingredient_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("allergens <@ ARRAY['peanut', 'tree_nuts', 'milk', 'egg', 'fish', 'crustaceans', 'molluscs', 'soy', 'gluten', 'sesame', 'mustard', 'celery', 'sulphites', 'lupin']::text[]", name=op.f('ck_ingredients_allergens_known')),
    sa.CheckConstraint("restriction_flags <@ ARRAY['vegetarian', 'vegan', 'pork', 'alcohol', 'lactose', 'gluten']::text[]", name=op.f('ck_ingredients_restriction_flags_known')),
    sa.CheckConstraint('(allergen_source IS NULL AND allergen_verified_by IS NULL AND allergen_verified_at IS NULL) OR (allergen_source IS NOT NULL AND allergen_verified_by IS NOT NULL AND allergen_verified_at IS NOT NULL)', name=op.f('ck_ingredients_allergen_verification_complete')),
    sa.CheckConstraint('density_g_per_ml IS NULL OR density_g_per_ml > 0', name=op.f('ck_ingredients_density_positive')),
    sa.CheckConstraint('kcal_100 >= 0 AND protein_100 >= 0 AND carbs_100 >= 0 AND fat_100 >= 0 AND fiber_100 >= 0', name=op.f('ck_ingredients_nutrition_not_negative')),
    sa.CheckConstraint('seasonality <@ ARRAY[1,2,3,4,5,6,7,8,9,10,11,12]::smallint[]', name=op.f('ck_ingredients_seasonality_months')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingredients'))
    )
    op.create_index('ix_ingredients_allergens', 'ingredients', ['allergens'], unique=False, postgresql_using='gin')
    op.create_index('ix_ingredients_category_status', 'ingredients', ['category', 'status'], unique=False)
    op.create_index(op.f('ix_ingredients_slug'), 'ingredients', ['slug'], unique=True)
    op.create_table('nutrition_profiles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('external_user_id', sa.String(length=128), nullable=True),
    sa.Column('goal', sa.Enum('weight_loss', 'weight_maintenance', 'weight_gain', 'muscle_gain', 'balanced_diet', 'habit_improvement', name='goal'), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('height_cm', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('sex', sa.Enum('male', 'female', 'unspecified', name='sex'), nullable=False),
    sa.Column('activity_level', sa.Enum('sedentary', 'lightly_active', 'moderately_active', 'very_active', 'extremely_active', name='activity_level'), nullable=False),
    sa.Column('meals_per_day', sa.Integer(), nullable=False),
    sa.Column('household_size', sa.Integer(), nullable=False),
    sa.Column('daily_budget', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('district', sa.String(length=120), nullable=True),
    sa.Column('travel_radius_km', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('declared_pregnancy', sa.Boolean(), nullable=False),
    sa.Column('declared_breastfeeding', sa.Boolean(), nullable=False),
    sa.Column('declared_medical_condition', sa.Boolean(), nullable=False),
    sa.Column('disclaimer_accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('daily_budget IS NULL OR daily_budget >= 0', name=op.f('ck_nutrition_profiles_budget_not_negative')),
    sa.CheckConstraint('height_cm > 0 AND height_cm BETWEEN 100 AND 250', name=op.f('ck_nutrition_profiles_height_range')),
    sa.CheckConstraint('household_size >= 1', name=op.f('ck_nutrition_profiles_household_size_positive')),
    sa.CheckConstraint('meals_per_day BETWEEN 3 AND 5', name=op.f('ck_nutrition_profiles_meals_per_day_range')),
    sa.CheckConstraint('weight_kg > 0 AND weight_kg BETWEEN 25 AND 300', name=op.f('ck_nutrition_profiles_weight_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nutrition_profiles'))
    )
    op.create_index(op.f('ix_nutrition_profiles_external_user_id'), 'nutrition_profiles', ['external_user_id'], unique=True)
    op.create_table('scoring_weight_sets',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('weights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scoring_weight_sets')),
    sa.UniqueConstraint('version', name=op.f('uq_scoring_weight_sets_version'))
    )
    op.create_index('uq_scoring_weight_sets_active', 'scoring_weight_sets', ['is_active'], unique=True, postgresql_where='is_active')
    op.create_table('dietary_preferences',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('prefer_local_products', sa.Boolean(), nullable=False),
    sa.Column('prefer_quick_dishes', sa.Boolean(), nullable=False),
    sa.Column('prefer_easy_dishes', sa.Boolean(), nullable=False),
    sa.Column('prefer_economical_dishes', sa.Boolean(), nullable=False),
    sa.Column('vegetarian_preference', sa.Boolean(), nullable=False),
    sa.Column('preferred_cuisines', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('preferred_protein_types', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('max_food_frequency', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('max_food_frequency IS NULL OR max_food_frequency > 0', name=op.f('ck_dietary_preferences_max_food_frequency_positive')),
    sa.ForeignKeyConstraint(['profile_id'], ['nutrition_profiles.id'], name=op.f('fk_dietary_preferences_profile_id_nutrition_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dietary_preferences')),
    sa.UniqueConstraint('profile_id', name=op.f('uq_dietary_preferences_profile_id'))
    )
    op.create_table('dietary_restrictions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('restriction_type', sa.Enum('vegetarian', 'vegan', 'no_pork', 'no_alcohol', 'lactose_free', 'gluten_free', 'religious', 'forbidden_food', 'custom', name='restriction_type'), nullable=False),
    sa.Column('custom_label', sa.String(length=255), nullable=True),
    sa.Column('normalized_ingredient_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('normalized_tags', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('is_normalized', sa.Boolean(), nullable=False),
    sa.Column('needs_admin_review', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("restriction_type NOT IN ('custom', 'religious', 'forbidden_food') OR custom_label IS NOT NULL", name=op.f('ck_dietary_restrictions_custom_requires_label')),
    sa.ForeignKeyConstraint(['profile_id'], ['nutrition_profiles.id'], name=op.f('fk_dietary_restrictions_profile_id_nutrition_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dietary_restrictions'))
    )
    op.create_index('ix_dietary_restrictions_pending_review', 'dietary_restrictions', ['needs_admin_review'], unique=False, postgresql_where='needs_admin_review')
    op.create_index(op.f('ix_dietary_restrictions_profile_id'), 'dietary_restrictions', ['profile_id'], unique=False)
    op.create_table('dish_allergens',
    sa.Column('dish_id', sa.UUID(), nullable=False),
    sa.Column('allergen', sa.Enum('peanut', 'tree_nuts', 'milk', 'egg', 'fish', 'crustaceans', 'molluscs', 'soy', 'gluten', 'sesame', 'mustard', 'celery', 'sulphites', 'lupin', name='allergen'), nullable=False),
    sa.Column('is_manual', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], name=op.f('fk_dish_allergens_dish_id_dishes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dish_id', 'allergen', name=op.f('pk_dish_allergens'))
    )
    op.create_table('dish_embeddings',
    sa.Column('dish_id', sa.UUID(), nullable=False),
    sa.Column('embedding', postgresql.ARRAY(sa.REAL()), nullable=True),
    sa.Column('embedding_model', sa.String(length=120), nullable=True),
    sa.Column('embedding_version', sa.String(length=16), nullable=True),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], name=op.f('fk_dish_embeddings_dish_id_dishes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dish_id', name=op.f('pk_dish_embeddings'))
    )
    op.create_table('dish_ingredients',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('dish_id', sa.UUID(), nullable=False),
    sa.Column('ingredient_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=40), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_dish_ingredients_quantity_positive')),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], name=op.f('fk_dish_ingredients_dish_id_dishes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], name=op.f('fk_dish_ingredients_ingredient_id_ingredients'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dish_ingredients')),
    sa.UniqueConstraint('dish_id', 'ingredient_id', name=op.f('uq_dish_ingredients_dish_id_ingredient_id'))
    )
    op.create_index(op.f('ix_dish_ingredients_dish_id'), 'dish_ingredients', ['dish_id'], unique=False)
    op.create_index(op.f('ix_dish_ingredients_ingredient_id'), 'dish_ingredients', ['ingredient_id'], unique=False)
    op.create_table('dish_steps',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('dish_id', sa.UUID(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=True),
    sa.CheckConstraint('step_number > 0', name=op.f('ck_dish_steps_step_number_positive')),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], name=op.f('fk_dish_steps_dish_id_dishes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dish_steps')),
    sa.UniqueConstraint('dish_id', 'step_number', name=op.f('uq_dish_steps_dish_id_step_number'))
    )
    op.create_index(op.f('ix_dish_steps_dish_id'), 'dish_steps', ['dish_id'], unique=False)
    op.create_table('dish_tags',
    sa.Column('dish_id', sa.UUID(), nullable=False),
    sa.Column('tag', sa.Enum('economical', 'quick', 'local', 'high_protein', 'low_carb', 'vegetarian', 'vegan', 'lactose_free', 'gluten_free', 'muscle_gain', 'weight_loss', 'family_meal', 'make_ahead', 'seasonal', name='dish_tag'), nullable=False),
    sa.Column('is_derived', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], name=op.f('fk_dish_tags_dish_id_dishes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dish_id', 'tag', name=op.f('pk_dish_tags'))
    )
    op.create_table('disliked_ingredients',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('ingredient_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], name=op.f('fk_disliked_ingredients_ingredient_id_ingredients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['nutrition_profiles.id'], name=op.f('fk_disliked_ingredients_profile_id_nutrition_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id', 'ingredient_id', name=op.f('pk_disliked_ingredients'))
    )
    op.create_table('favorite_ingredients',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('ingredient_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], name=op.f('fk_favorite_ingredients_ingredient_id_ingredients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['nutrition_profiles.id'], name=op.f('fk_favorite_ingredients_profile_id_nutrition_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id', 'ingredient_id', name=op.f('pk_favorite_ingredients'))
    )
    op.create_table('ingredient_aliases',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ingredient_id', sa.UUID(), nullable=False),
    sa.Column('alias', sa.String(length=200), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], name=op.f('fk_ingredient_aliases_ingredient_id_ingredients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingredient_aliases')),
    sa.UniqueConstraint('ingredient_id', 'alias', name=op.f('uq_ingredient_aliases_ingredient_id_alias'))
    )
    op.create_index(op.f('ix_ingredient_aliases_ingredient_id'), 'ingredient_aliases', ['ingredient_id'], unique=False)
    op.create_table('ingredient_unit_conversions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ingredient_id', sa.UUID(), nullable=False),
    sa.Column('from_unit', sa.String(length=40), nullable=False),
    sa.Column('to_unit', sa.String(length=40), nullable=False),
    sa.Column('factor', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('factor > 0', name=op.f('ck_ingredient_unit_conversions_factor_positive')),
    sa.CheckConstraint('from_unit <> to_unit', name=op.f('ck_ingredient_unit_conversions_units_differ')),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], name=op.f('fk_ingredient_unit_conversions_ingredient_id_ingredients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingredient_unit_conversions')),
    sa.UniqueConstraint('ingredient_id', 'from_unit', 'to_unit', name=op.f('uq_ingredient_unit_conversions_ingredient_id_from_unit_to_unit'))
    )
    op.create_index(op.f('ix_ingredient_unit_conversions_ingredient_id'), 'ingredient_unit_conversions', ['ingredient_id'], unique=False)
    op.create_table('meal_plans',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('external_user_id', sa.String(length=128), nullable=True),
    sa.Column('profile_id', sa.UUID(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('days_count', sa.Integer(), nullable=False),
    sa.Column('household_size', sa.Integer(), nullable=False),
    sa.Column('goal', sa.Enum('weight_loss', 'weight_maintenance', 'weight_gain', 'muscle_gain', 'balanced_diet', 'habit_improvement', name='goal'), nullable=False),
    sa.Column('kcal_target', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('status', sa.Enum('generating', 'active', 'obsolete', 'archived', 'failed', name='meal_plan_status'), nullable=False),
    sa.Column('total_cost_min', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_cost_max', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cost_confidence', sa.Enum('estimated', 'observed', name='cost_confidence'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('parent_plan_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('days_count > 0', name=op.f('ck_meal_plans_days_count_positive')),
    sa.CheckConstraint('end_date >= start_date', name=op.f('ck_meal_plans_period_ordered')),
    sa.CheckConstraint('household_size >= 1', name=op.f('ck_meal_plans_household_size_positive')),
    sa.CheckConstraint('total_cost_min IS NULL OR total_cost_max IS NULL OR total_cost_max >= total_cost_min', name=op.f('ck_meal_plans_cost_range_ordered')),
    sa.CheckConstraint('version >= 1', name=op.f('ck_meal_plans_version_positive')),
    sa.ForeignKeyConstraint(['parent_plan_id'], ['meal_plans.id'], name=op.f('fk_meal_plans_parent_plan_id_meal_plans'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['profile_id'], ['nutrition_profiles.id'], name=op.f('fk_meal_plans_profile_id_nutrition_profiles'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meal_plans'))
    )
    op.create_index(op.f('ix_meal_plans_external_user_id'), 'meal_plans', ['external_user_id'], unique=False)
    op.create_index('ix_meal_plans_user_status', 'meal_plans', ['external_user_id', 'status'], unique=False)
    op.create_table('nutrition_profile_history',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('changed_fields', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('previous_values', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['nutrition_profiles.id'], name=op.f('fk_nutrition_profile_history_profile_id_nutrition_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nutrition_profile_history'))
    )
    op.create_index(op.f('ix_nutrition_profile_history_changed_at'), 'nutrition_profile_history', ['changed_at'], unique=False)
    op.create_index(op.f('ix_nutrition_profile_history_profile_id'), 'nutrition_profile_history', ['profile_id'], unique=False)
    op.create_table('nutrition_targets',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('bmr', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('tdee', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('kcal_target', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('protein_g', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('carbs_g', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('fat_g', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('safety_floor_applied', sa.Boolean(), nullable=False),
    sa.Column('formula', sa.String(length=64), nullable=False),
    sa.Column('formula_version', sa.String(length=16), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('kcal_target > 0', name=op.f('ck_nutrition_targets_kcal_target_positive')),
    sa.CheckConstraint('protein_g >= 0 AND carbs_g >= 0 AND fat_g >= 0', name=op.f('ck_nutrition_targets_macros_not_negative')),
    sa.ForeignKeyConstraint(['profile_id'], ['nutrition_profiles.id'], name=op.f('fk_nutrition_targets_profile_id_nutrition_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nutrition_targets'))
    )
    op.create_index(op.f('ix_nutrition_targets_computed_at'), 'nutrition_targets', ['computed_at'], unique=False)
    op.create_index(op.f('ix_nutrition_targets_profile_id'), 'nutrition_targets', ['profile_id'], unique=False)
    op.create_table('user_allergies',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('allergen', sa.Enum('peanut', 'tree_nuts', 'milk', 'egg', 'fish', 'crustaceans', 'molluscs', 'soy', 'gluten', 'sesame', 'mustard', 'celery', 'sulphites', 'lupin', name='allergen'), nullable=False),
    sa.Column('declared_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['nutrition_profiles.id'], name=op.f('fk_user_allergies_profile_id_nutrition_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_allergies')),
    sa.UniqueConstraint('profile_id', 'allergen', name=op.f('uq_user_allergies_profile_id_allergen'))
    )
    op.create_index(op.f('ix_user_allergies_profile_id'), 'user_allergies', ['profile_id'], unique=False)
    op.create_table('generation_jobs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('external_user_id', sa.String(length=128), nullable=True),
    sa.Column('plan_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'running', 'succeeded', 'failed', name='job_status'), nullable=False),
    sa.Column('request_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['meal_plans.id'], name=op.f('fk_generation_jobs_plan_id_meal_plans'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_generation_jobs'))
    )
    op.create_index(op.f('ix_generation_jobs_correlation_id'), 'generation_jobs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_generation_jobs_external_user_id'), 'generation_jobs', ['external_user_id'], unique=False)
    op.create_table('meal_plan_days',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('day_index', sa.Integer(), nullable=False),
    sa.Column('day_date', sa.Date(), nullable=False),
    sa.Column('kcal_total', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('protein_total', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('carbs_total', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('fat_total', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('daily_tip', sa.Text(), nullable=True),
    sa.CheckConstraint('day_index >= 0', name=op.f('ck_meal_plan_days_day_index_not_negative')),
    sa.ForeignKeyConstraint(['plan_id'], ['meal_plans.id'], name=op.f('fk_meal_plan_days_plan_id_meal_plans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meal_plan_days')),
    sa.UniqueConstraint('plan_id', 'day_index', name=op.f('uq_meal_plan_days_plan_id_day_index'))
    )
    op.create_index(op.f('ix_meal_plan_days_plan_id'), 'meal_plan_days', ['plan_id'], unique=False)
    op.create_table('plan_validations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('phase', sa.String(length=32), nullable=False),
    sa.Column('outcome', sa.Enum('validated', 'corrected', 'rejected', 'regeneration_requested', name='validation_outcome'), nullable=False),
    sa.Column('failed_checks', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('corrections', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_food_safety_incident', sa.Boolean(), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("phase IN ('post_selection', 'post_llm')", name=op.f('ck_plan_validations_phase_known')),
    sa.CheckConstraint('failed_checks <@ ARRAY[1,2,3,4,5,6,7,8,9,10,11]::integer[]', name=op.f('ck_plan_validations_failed_checks_known')),
    sa.ForeignKeyConstraint(['plan_id'], ['meal_plans.id'], name=op.f('fk_plan_validations_plan_id_meal_plans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_validations'))
    )
    op.create_index('ix_plan_validations_incidents', 'plan_validations', ['is_food_safety_incident'], unique=False, postgresql_where='is_food_safety_incident')
    op.create_index(op.f('ix_plan_validations_plan_id'), 'plan_validations', ['plan_id'], unique=False)
    op.create_table('recommendation_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('scoring_version', sa.String(length=32), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('llm_call_count', sa.Integer(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('used_fallback', sa.Boolean(), nullable=False),
    sa.Column('random_seed', sa.Integer(), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('cost >= 0', name=op.f('ck_recommendation_runs_cost_not_negative')),
    sa.CheckConstraint('input_tokens >= 0 AND output_tokens >= 0', name=op.f('ck_recommendation_runs_tokens_not_negative')),
    sa.CheckConstraint('llm_call_count <= 1', name=op.f('ck_recommendation_runs_single_llm_call_per_plan')),
    sa.ForeignKeyConstraint(['plan_id'], ['meal_plans.id'], name=op.f('fk_recommendation_runs_plan_id_meal_plans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendation_runs'))
    )
    op.create_index(op.f('ix_recommendation_runs_correlation_id'), 'recommendation_runs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_recommendation_runs_plan_id'), 'recommendation_runs', ['plan_id'], unique=False)
    op.create_table('meal_plan_meals',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('day_id', sa.UUID(), nullable=False),
    sa.Column('slot', sa.Enum('breakfast', 'morning_snack', 'lunch', 'afternoon_snack', 'dinner', name='meal_slot'), nullable=False),
    sa.Column('dish_id', sa.UUID(), nullable=True),
    sa.Column('dish_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('servings', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('kcal', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('protein_g', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('carbs_g', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('fat_g', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('tracked_status', sa.Enum('pending', 'followed', 'skipped', 'replaced', name='tracked_status'), nullable=False),
    sa.Column('consumed_quantity', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.CheckConstraint("dish_snapshot <> '{}'::jsonb", name=op.f('ck_meal_plan_meals_snapshot_not_empty')),
    sa.CheckConstraint('servings > 0', name=op.f('ck_meal_plan_meals_servings_positive')),
    sa.ForeignKeyConstraint(['day_id'], ['meal_plan_days.id'], name=op.f('fk_meal_plan_meals_day_id_meal_plan_days'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], name=op.f('fk_meal_plan_meals_dish_id_dishes'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meal_plan_meals')),
    sa.UniqueConstraint('day_id', 'slot', name=op.f('uq_meal_plan_meals_day_id_slot'))
    )
    op.create_index(op.f('ix_meal_plan_meals_day_id'), 'meal_plan_meals', ['day_id'], unique=False)
    op.create_table('recommendation_candidates',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('day_index', sa.Integer(), nullable=False),
    sa.Column('slot', sa.Enum('breakfast', 'morning_snack', 'lunch', 'afternoon_snack', 'dinner', name='meal_slot'), nullable=False),
    sa.Column('dish_id', sa.UUID(), nullable=True),
    sa.Column('score', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('score_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('selected', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], name=op.f('fk_recommendation_candidates_dish_id_dishes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['recommendation_runs.id'], name=op.f('fk_recommendation_candidates_run_id_recommendation_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendation_candidates'))
    )
    op.create_index(op.f('ix_recommendation_candidates_run_id'), 'recommendation_candidates', ['run_id'], unique=False)
    op.create_index('ix_recommendation_candidates_run_slot', 'recommendation_candidates', ['run_id', 'day_index', 'slot'], unique=False)
    op.create_table('user_meal_feedback',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('meal_id', sa.UUID(), nullable=False),
    sa.Column('feedback_type', sa.Enum('accepted', 'rejected', 'replaced', 'too_expensive', 'ingredient_unavailable', 'disliked', 'too_difficult', 'too_long', 'allergy_issue', 'other', name='feedback_type'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['meal_id'], ['meal_plan_meals.id'], name=op.f('fk_user_meal_feedback_meal_id_meal_plan_meals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_meal_feedback'))
    )
    op.create_index('ix_user_meal_feedback_allergy', 'user_meal_feedback', ['feedback_type'], unique=False, postgresql_where="feedback_type = 'allergy_issue'")
    op.create_index(op.f('ix_user_meal_feedback_meal_id'), 'user_meal_feedback', ['meal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_meal_feedback_meal_id'), table_name='user_meal_feedback')
    op.drop_index('ix_user_meal_feedback_allergy', table_name='user_meal_feedback', postgresql_where="feedback_type = 'allergy_issue'")
    op.drop_table('user_meal_feedback')
    op.drop_index('ix_recommendation_candidates_run_slot', table_name='recommendation_candidates')
    op.drop_index(op.f('ix_recommendation_candidates_run_id'), table_name='recommendation_candidates')
    op.drop_table('recommendation_candidates')
    op.drop_index(op.f('ix_meal_plan_meals_day_id'), table_name='meal_plan_meals')
    op.drop_table('meal_plan_meals')
    op.drop_index(op.f('ix_recommendation_runs_plan_id'), table_name='recommendation_runs')
    op.drop_index(op.f('ix_recommendation_runs_correlation_id'), table_name='recommendation_runs')
    op.drop_table('recommendation_runs')
    op.drop_index(op.f('ix_plan_validations_plan_id'), table_name='plan_validations')
    op.drop_index('ix_plan_validations_incidents', table_name='plan_validations', postgresql_where='is_food_safety_incident')
    op.drop_table('plan_validations')
    op.drop_index(op.f('ix_meal_plan_days_plan_id'), table_name='meal_plan_days')
    op.drop_table('meal_plan_days')
    op.drop_index(op.f('ix_generation_jobs_external_user_id'), table_name='generation_jobs')
    op.drop_index(op.f('ix_generation_jobs_correlation_id'), table_name='generation_jobs')
    op.drop_table('generation_jobs')
    op.drop_index(op.f('ix_user_allergies_profile_id'), table_name='user_allergies')
    op.drop_table('user_allergies')
    op.drop_index(op.f('ix_nutrition_targets_profile_id'), table_name='nutrition_targets')
    op.drop_index(op.f('ix_nutrition_targets_computed_at'), table_name='nutrition_targets')
    op.drop_table('nutrition_targets')
    op.drop_index(op.f('ix_nutrition_profile_history_profile_id'), table_name='nutrition_profile_history')
    op.drop_index(op.f('ix_nutrition_profile_history_changed_at'), table_name='nutrition_profile_history')
    op.drop_table('nutrition_profile_history')
    op.drop_index('ix_meal_plans_user_status', table_name='meal_plans')
    op.drop_index(op.f('ix_meal_plans_external_user_id'), table_name='meal_plans')
    op.drop_table('meal_plans')
    op.drop_index(op.f('ix_ingredient_unit_conversions_ingredient_id'), table_name='ingredient_unit_conversions')
    op.drop_table('ingredient_unit_conversions')
    op.drop_index(op.f('ix_ingredient_aliases_ingredient_id'), table_name='ingredient_aliases')
    op.drop_table('ingredient_aliases')
    op.drop_table('favorite_ingredients')
    op.drop_table('disliked_ingredients')
    op.drop_table('dish_tags')
    op.drop_index(op.f('ix_dish_steps_dish_id'), table_name='dish_steps')
    op.drop_table('dish_steps')
    op.drop_index(op.f('ix_dish_ingredients_ingredient_id'), table_name='dish_ingredients')
    op.drop_index(op.f('ix_dish_ingredients_dish_id'), table_name='dish_ingredients')
    op.drop_table('dish_ingredients')
    op.drop_table('dish_embeddings')
    op.drop_table('dish_allergens')
    op.drop_index(op.f('ix_dietary_restrictions_profile_id'), table_name='dietary_restrictions')
    op.drop_index('ix_dietary_restrictions_pending_review', table_name='dietary_restrictions', postgresql_where='needs_admin_review')
    op.drop_table('dietary_restrictions')
    op.drop_table('dietary_preferences')
    op.drop_index('uq_scoring_weight_sets_active', table_name='scoring_weight_sets', postgresql_where='is_active')
    op.drop_table('scoring_weight_sets')
    op.drop_index(op.f('ix_nutrition_profiles_external_user_id'), table_name='nutrition_profiles')
    op.drop_table('nutrition_profiles')
    op.drop_index(op.f('ix_ingredients_slug'), table_name='ingredients')
    op.drop_index('ix_ingredients_category_status', table_name='ingredients')
    op.drop_index('ix_ingredients_allergens', table_name='ingredients', postgresql_using='gin')
    op.drop_table('ingredients')
    op.drop_index('ix_dishes_status_meal_types', table_name='dishes')
    op.drop_index(op.f('ix_dishes_slug'), table_name='dishes')
    op.drop_index('ix_dishes_meal_types_gin', table_name='dishes', postgresql_using='gin')
    op.drop_table('dishes')
    op.drop_index('ix_audit_logs_user_occurred_at', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_occurred_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_correlation_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_action_occurred_at', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
